version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80" # Mapeie a porta 8082 do host para a porta 80 do contêiner
    volumes:
      - .:/var/www/html/atestadosManager # Monte o diretório do projeto no contêiner
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: